### ISSUE TITLE
Bad identation of a mapping entry [BUG] 

### ISSUE THREAD

**Issue by lappat** [amaximus/garbage-collection-card#91]
**Describe the bug**
can't see the folder 

**To Reproduce**

add the following to my configuration.yaml

resources:
  //When using HACS installation method
  - {type: js, url: '/www/community/garbage-collection-card/garbage-collection-card.js'}

**Expected behavior**

to work

![image](https://user-images.githubusercontent.com/61441238/153533403-25b1275d-61c9-441b-b1bc-6a598f659081.png)

**Environment (please complete the following information):**
 - Garbage Collection Card version: 1.20.1
 - Browser: Edge
 - Browser language: English

**Additional context**

**Comment by amaximus** [comment]
Please use ```type: module``` instead of ```type: js```.
I updated the README.

Please get back to me with results.

**Comment by lappat** [comment]
after update with the following i don't have a error on the config file, but when a try to restart i have the following log;

line added note creating a error inside the file, i,m using studio code server:

![image](https://user-images.githubusercontent.com/61441238/153603608-5c228ed4-e34d-4ad5-ac37-66f009492333.png)

Error log:

Logger: homeassistant.components.websocket_api.http.connection
Source: components/hassio/__init__.py:609
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 8:48:02 AM (2 occurrences)
Last logged: 8:48:09 AM

[140691621942320] The system cannot restart because the configuration is not valid: Integration error: resources - Integration 'resources' not found.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 190, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1630, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1667, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/components/hassio/__init__.py", line 609, in async_handle_core_service
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: The system cannot restart because the configuration is not valid: Integration error: resources - Integration 'resources' not found.

Thnaks for your quick reply,

Patrick

**Comment by amaximus** [comment]
If you installed it via HACS then the right URL should be:
```
    - {type: module, url: '/hacsfiles/garbage-collection-card/garbage-collection-card.js'}
```

**Comment by lappat** [comment]
Hi,

i'm still having the following;

![image](https://user-images.githubusercontent.com/61441238/153605215-e78466e0-0892-47db-bcf7-6a82951ca9ac.png)

Card install in HACS:

![image](https://user-images.githubusercontent.com/61441238/153605309-bad55604-c4e9-4d15-b40f-a198528e5127.png)

No error when adding in configuration file:

![image](https://user-images.githubusercontent.com/61441238/153605423-124201ae-5a95-4d1d-b429-4901583a9206.png)

Don't have the HACS in my folder in CONFIG:

![image](https://user-images.githubusercontent.com/61441238/153605577-78f67c0c-0663-4b8b-a45e-904e5915aa03.png)

Let me know,

**Comment by lappat** [comment]
do you think a need to add in Frontend?

![image](https://user-images.githubusercontent.com/61441238/153606032-f1bd9bf2-b7d2-4098-afd4-97635eb66ccd.png)

**Comment by amaximus** [comment]
Resources should go into the lovelace section.

![capture_02112022_151003](https://user-images.githubusercontent.com/2511168/153606521-de6a0a38-a48a-484a-91ab-1bb625c9362f.jpg)

**Comment by lappat** [comment]
it is working now!

thanks for your support

![image](https://user-images.githubusercontent.com/61441238/153607462-663aeb07-636a-48ae-99c4-cd220feb7262.png)

**Comment by amaximus** [comment]
Glad to hear that.
